name: Deploy Page
#yaml auto formatting is gross;
on:
    push:
        branches: [main]

jobs:
    publish:
        concurrency:
            group: deploy
            cancel-in-progress: true
        permissions:
            contents: write
        runs-on: macOS-latest #using windows fixed the permissions error
        steps:
            - uses: actions/checkout@v6
            - name: Build Portfolio
              run: npm ci --force && npm exec vite build #  installs vite and generates the three.js files
            - name: Deploy Portfolio
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: dist # directory with index.html and other files to deploy
                  branch: deployment # branch that deploys it
